### ISSUE TITLE
store 方案讨论

### ISSUE THREAD

**Issue by transtone** [zfxmnb/westore#1]
最近一直在找微信小程序的 store 方案，有这么几个：
1.  https://github.com/phonycode/wenaox  能用，但使用方式非标准化
2. https://github.com/Tencent/omi/tree/master/packages/omix 腾讯自己人开发的，方便，但不是 vuex 语法。
3. https://github.com/dao42/wechat-weapp-mobx 直接引入 mobx，store语法复杂。
4. https://github.com/didi/mpx 也是包装了一下 mobx，模拟了 vuex 语法。只是必须在其框架内使用，不能作组件引用。

看到您的这个项目，非常惊喜，终于有一个简单又仿 vuex 语法的 store 方案了。可否请教一下，这个方案的初衷与特点是什么？后期会一直维护吗？

**Comment by zfxmnb** [comment]
你好，最近一段时间没有关注Issues，因为我最近也在跟几个小程序项目，近些天重新对小程序这块的状态管理方案去旧崇新，发现这个工具还存在很多问题，所以又重新捣鼓了一个新的状态管理，感觉更适合原生小程序的开发，如果有兴趣可以去看看，并提些宝贵意见。[wxStore](https://github.com/zfxmnb/wxStore#readme)
